# Run this faster because it can run on container based infra.
sudo: false
language: node_js
node_js:
  - "iojs"
  - "4.0"
  - "4.1"
script:
  - npm run coverage
after_script:
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info
